basePath: /
consumes: [application/json]
definitions:
  ErrorResponse:
    properties:
      message: {type: string}
    required: [message]
  HelloWorldResponse:
    properties:
      message: {type: string}
    required: [message]
host: localhost:40005
info: {title: Sororok, version: 0.0.1}
paths:
  /hello:
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
      - {description: The name of the person to whom to say hello, in: query, name: name,
        required: false, type: string}
      responses:
        '200':
          description: Success
          schema: {$ref: '#/definitions/HelloWorldResponse'}
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /repository:
    get:
      description: Returns 'repository' to the caller
      operationId: hello
      parameters:
      - {description: The name of the person to whom to say hello, in: query, name: name,
        required: false, type: string}
      responses:
        '200':
          description: Success
          schema: {$ref: '#/definitions/HelloWorldResponse'}
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /swagger: {x-swagger-pipe: swagger_raw}
produces: [application/json]
schemes: [http]
swagger: '2.0'
