basePath: /
consumes: [application/json]
definitions:
  ErrorResponse:
    properties:
      message: {type: string}
    required: [message]
host: 45.63.120.140:40005
info: {title: Sororok, version: 0.0.1}
paths:
  /member/info:
    get:
      description: "회원정보 불러오기"
      operationId: info
      parameters:
      - {in: query, name: memberId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              memberId: {type: integer}
              name: {type: string}
              phone: {type: string}
              email: {type: string}
              imageName: {type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /member/history:
    get:
      description: "\uCD5C\uADFC \uC18C\uC2DD \uAC00\uC838\uC624\uAE30"
      operationId: history
      parameters:
      - {in: query, name: memberId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              content: {description: "\uD45C\uC2DC\uD560 \uB0B4\uC6A9", type: string}
              date: {description: "\uC18C\uC2DD \uC2DC\uAC04", type: string}
              seq_no: {description: "\uC18C\uC2DD \uC778\uB371\uC2A4", type: integer}
            required: [seq_no]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /member/join:
    put:
      consumes: [multipart/form-data]
      description: "\uD68C\uC6D0\uAC00\uC785."
      operationId: join
      parameters:
      - {description: phone, in: formData, name: phone, required: true, type: string}
      - {description: name, in: formData, name: name, required: true, type: string}
      - {description: email, in: formData, name: email, required: true, type: string}
      - {description: "\uB85C\uADF8\uC778 \uC2DC\uB3C4\uD588\uB358 \uC18C\uC15C\uB85C\
          \uADF8\uC778 \uC885\uB958", in: formData, name: loginType, required: true,
        type: string}
      - {description: "\uB85C\uADF8\uC778 \uC2DC\uB3C4\uD588\uC744\uB54C \uB118\uC5B4\
          \uC654\uB358 UID", in: formData, name: loginUid, required: true, type: string}
      - {description: profile Image, in: formData, name: memberImage, required: false,
        type: file}
      - {description: profile Image, in: formData, name: imageUrl, required: false,
        type: string}
      responses:
        '200':
          description: Success
          schema:
            properties:
              eamil: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              imageName: {description: "\uBA64\uBC84 \uD504\uB85C\uD544 \uC774\uBBF8\
                  \uC9C0", type: string}
              memberId: {type: integer}
              name: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              phone: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /member/login:
    post:
      consumes: [application/json]
      description: "\uB85C\uADF8\uC778"
      operationId: login
      parameters:
      - description: "\uC774\uBBF8 \uAC00\uC785\uB41C \uD68C\uC6D0\uC778\uC9C0 \uD655\
          \uC778"
        in: body
        name: data
        schema:
          properties:
            type: {description: 0 - google 1 - kakao 2 - naver, type: string}
            uid: {type: string}
          required: [type, uid]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              eamil: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              imageName: {description: "\uBA64\uBC84 \uD504\uB85C\uD544 \uC774\uBBF8\
                  \uC9C0", type: string}
              memberId: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0\
                  \ \uC54A\uC744\uB54C\uB294 -1 \uC74C\uC218\uAC12\uC73C\uB85C \uBCF4\
                  \uB0C4", type: integer}
              name: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              phone: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /member/remove:
    put:
      consumes: [application/json]
      description: "\uC18C\uB85C\uB85D \uD68C\uC6D0 \uD0C8\uD1F4"
      operationId: remove
      parameters:
      - description: "\uC18C\uB85C\uB85D \uD68C\uC6D0 \uD0C8\uD1F4 \uD30C\uB77C\uBBF8\
          \uD130"
        in: body
        name: data
        schema:
          properties:
            memberId: {type: integer}
          required: [memberId]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC131\uACF5\uC2DC 0 \uC2E4\uD328\uC2DC \uC74C\uC218",
                type: integer}
              message: {type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /member/update:
    put:
      consumes: [multipart/form-data]
      description: "\uBA64\uBC84\uC815\uBCF4 \uC5C5\uB370\uC774\uD2B8"
      operationId: update
      parameters:
      - {description: phone, in: formData, name: phone, required: true, type: string}
      - {description: name, in: formData, name: name, required: true, type: string}
      - {description: email, in: formData, name: email, required: true, type: string}
      - {description: "\uC218\uC815\uD558\uB824\uB294 \uBA64\uBC84 \uC544\uC774\uB514",
        in: formData, name: memberId, required: true, type: integer}
      - {description: profile Image, in: formData, name: memberImage, required: false,
        type: file}
      responses:
        '200':
          description: Success
          schema:
            properties:
              eamil: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              imageName: {description: "\uBA64\uBC84 \uD504\uB85C\uD544 \uC774\uBBF8\
                  \uC9C0", type: string}
              memberId: {type: integer}
              name: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
              phone: {description: "\uD68C\uC6D0\uAC00\uC785\uB418\uC788\uC9C0 \uC54A\
                  \uC744\uB54C\uB294 ''", type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: member
  /repository/changeAuthority:
    put:
      consumes: [application/json]
      description: "\uADF8\uB8F9\uAD00\uB9AC\uC790 \uBCC0\uACBD"
      operationId: changeAuthority
      parameters:
      - description: "\uC6D0\uB798\uC8FC\uC778\uACFC \uBC14\uB014\uC8FC\uC778 \uC815\
          \uBCF4\uB97C \uBCF4\uB0B4\uC57C \uD568"
        in: body
        name: data
        schema:
          properties:
            fromMemberId: {description: "\uC6D0\uB798 \uC8FC\uC778", type: integer}
            repositoryId: {type: integer}
            toMemberId: {description: "\uBC14\uB014 \uC8FC\uC778", type: integer}
          required: [fromMemberId, toMemberId, repositoryId]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC131\uACF5\uC2DC 0 \uC2E4\uD328\uC2DC \uC74C\uC218",
                type: integer}
              message: {type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/code:
    get:
      description: "\uC800\uC7A5\uC18C \uCF54\uB4DC \uC0DD\uC131"
      operationId: createRepositoryCode
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC800\uC7A5\uC18C \uCF54\uB4DC", type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/create:
    put:
      consumes: [multipart/form-data]
      description: "\uC800\uC7A5\uC18C \uC0DD\uC131"
      operationId: createRepository
      parameters:
      - {description: "\uC800\uC7A5\uC18C\uC774\uB984", in: formData, name: name,
        required: true, type: string}
      - {description: "\uC800\uC7A5\uC18C\uCF54\uB4DC", in: formData, name: code,
        required: true, type: string}
      - {description: "\uC800\uC7A5\uC18C\uC0DD\uC131\uD55C\uC0AC\uB78C", in: formData,
        name: memberId, required: true, type: integer}
      - {description: "\uC800\uC7A5\uC18C\uC124\uBA85", in: formData, name: extraInfo,
        required: true, type: string}
      - {description: "\uC800\uC7A5\uC18C \uC774\uBBF8\uC9C0", in: formData, name: repositoryImage,
        required: false, type: file}
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {type: string}
              memberId: {type: integer}
              name: {type: string}
              repositoryId: {type: integer}
            required: [repositoryId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/destroy:
    post:
      consumes: [application/json]
      description: "\uADF8\uB8F9 \uD3ED\uD30C"
      operationId: destroyRepository
      parameters:
      - description: ''
        in: body
        name: data
        schema:
          properties:
            memberId: {type: integer}
            repositoryId: {type: integer}
          required: [memberId, repositoryId]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC2E4\uD328\uC2DC \uC74C\uC218 \uC131\uACF5\uC2DC\
                  \ 0", type: integer}
              message: {type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/detail:
    get:
      description: "\uC800\uC7A5\uC18C \uB0B4 \uBA64\uBC84 \uB9AC\uC2A4\uD2B8"
      operationId: retrieveRepositoryDetail
      parameters:
      - {in: query, name: repositoryId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              authority: {description: "\uC800\uC7A5\uC18C \uB0B4 \uBA64\uBC84 \uAD8C\
                  \uD55C", type: integer}
              email: {description: "\uBA64\uBC84 \uC774\uBA54\uC77C", type: string}
              imageName: {description: "\uBA64\uBC84\uC774\uBBF8\uC9C0", type: string}
              memberId: {description: "\uBA64\uBC84 \uC778\uB371\uC2A4", type: integer}
              name: {description: "\uBA64\uBC84 \uC774\uB984", type: string}
              phone: {description: "\uBA64\uBC84 \uC804\uD654\uBC88\uD638", type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/exit:
    post:
      consumes: [application/json]
      description: "\uADF8\uB8F9 \uB098\uAC00\uAE30"
      operationId: exitRepository
      parameters:
      - description: ''
        in: body
        name: data
        schema:
          properties:
            memberId: {type: integer}
            repositoryId: {type: integer}
          required: [memberId, repositoryId]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC2E4\uD328\uC2DC \uC74C\uC218 \uC131\uACF5\uC2DC\
                  \ 0", type: integer}
              message: {type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/join:
    put:
      consumes: [application/json]
      description: "\uC800\uC7A5\uC18C \uAC00\uC785"
      operationId: joinRepository
      parameters:
      - description: "\uBA64\uBC84\uAC00 \uC800\uC7A5\uC18C \uAC00\uC785\uD560 \uB54C"
        in: body
        name: data
        schema:
          properties:
            code: {type: string}
            memberId: {type: integer}
            repositoryId: {type: integer}
          required: [memberId, repositoryId, code]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              message: {description: "\uC2E4\uD328\uC2DC \uBA54\uC138\uC9C0 -1\uC77C\
                  \ \uACBD\uC6B0 \uCF54\uB4DC \uBD88\uC77C\uCE58, -2\uC77C \uACBD\uC6B0\
                  \ \uC774\uBBF8\uAC00\uC785\uB41C \uC800\uC7A5\uC18C", type: string}
              repositoryId: {description: "\uC131\uACF5\uC2DC \uAC00\uC785\uB41C \uC800\
                  \uC7A5\uC18C \uC544\uC774\uB514 \uB9AC\uD134 \uC2E4\uD328\uC2DC\
                  \ \uC74C\uC218 \uB9AC\uD134", type: integer}
            required: [repositoryId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/list:
    get:
      description: "\uAC00\uC785\uB41C \uC800\uC7A5\uC18C \uB9AC\uC2A4\uD2B8"
      operationId: retrieveRepositoryList
      parameters:
      - {in: query, name: memberId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              extra_info: {description: "\uC800\uC7A5\uC18C \uC124\uBA85", type: string}
              imageName: {description: "\uC800\uC7A5\uC18C \uC774\uBBF8\uC9C0", type: string}
              name: {description: "\uC800\uC7A5\uC18C \uC774\uB984", type: string}
              repositoryId: {description: "\uC800\uC7A5\uC18C \uC778\uB371\uC2A4",
                type: integer}
              authority: {description: "그룹 권한",
                type: integer}
              joinFlag: {description: "그룹 가입 여부",
                type: integer}
            required: [repositoryId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/memberSearch:
    get:
      description: "\uADF8\uB8F9\uB0B4 \uBA64\uBC84 \uAC80\uC0C9"
      operationId: retrieveRepositoryMember
      parameters:
      - {in: query, name: memberName, required: true, type: string}
      - {in: query, name: repositoryId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              authority: {description: "\uC800\uC7A5\uC18C \uB0B4 \uBA64\uBC84 \uAD8C\
                  \uD55C", type: integer}
              email: {description: "\uBA64\uBC84 \uC774\uBA54\uC77C", type: string}
              imageName: {description: "\uBA64\uBC84\uC774\uBBF8\uC9C0", type: string}
              memberId: {description: "\uBA64\uBC84 \uC778\uB371\uC2A4", type: integer}
              name: {description: "\uBA64\uBC84 \uC774\uB984", type: string}
              phone: {description: "\uBA64\uBC84 \uC804\uD654\uBC88\uD638", type: string}
            required: [memberId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/search:
    get:
      description: "\uC800\uC7A5\uC18C \uC774\uB984\uC73C\uB85C \uAC80\uC0C9"
      operationId: retrieveRepositoryName
      parameters:
      - {in: query, name: name, required: true, type: string}
      - {in: query, name: memberId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              extra_info: {description: "\uC800\uC7A5\uC18C \uC124\uBA85", type: string}
              imageName: {description: "\uC800\uC7A5\uC18C \uC774\uBBF8\uC9C0", type: string}
              name: {description: "\uC800\uC7A5\uC18C \uC774\uB984", type: string}
              repositoryId: {description: "\uC800\uC7A5\uC18C \uC778\uB371\uC2A4",
                type: integer}
              joinFlag: {type: integer}
            required: [repositoryId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/update:
    put:
      consumes: [application/json]
      description: "\uADF8\uB8F9\uC815\uBCF4 \uBCC0\uACBD"
      operationId: update
      parameters:
      - description: "\uD604\uC7AC\uB294 \uCF54\uB4DC\uB9CC \uBCC0\uACBD \uAC00\uB2A5"
        in: body
        name: data
        schema:
          properties:
            repositoryId: {type: integer}
          required: [repositoryId]
          type: object
      responses:
        '200':
          description: Success
          schema:
            properties:
              code: {description: "\uC131\uACF5\uC2DC 0 \uC2E4\uD328\uC2DC \uC74C\uC218",
                type: integer}
              groupCode: {type: string}
              message: {type: string}
            required: [code]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /repository/info:
    get:
      description: "그룹정보 가져오기"
      operationId: retrieveInfo
      parameters:
      - {in: query, name: repositoryId, required: true, type: integer}
      produces: [application/json, application/xml]
      responses:
        '200':
          description: Success
          schema:
            properties:
              repositoryId: {type: integer}
              name: {type: string}
              extra_info: {type: string}
              code: {type: string}
              imageName: {type: string}
            required: [repositoryId]
        default:
          description: Error
          schema: {$ref: '#/definitions/ErrorResponse'}
    x-swagger-router-controller: repository
  /swagger: {x-swagger-pipe: swagger_raw}
produces: [application/json]
schemes: [http]
swagger: '2.0'
